In [27]:
import person
print(person.name)

zack


In [31]:
import person
print(person.devices)

['laptop', 'smartphone', 'tablet']


In [32]:
from person import name, devices
print(name)
print(devices)

zack
['laptop', 'smartphone', 'tablet']


In [33]:
import importlib #reload kalo pakai ipynb
importlib.reload(person)

<module 'person' from '/Users/puputariana/Desktop/Hacktiv8/Assignments/Learning_Journal/Phas_ 0/Week_1/person.py'>

## Package
dalam package sudah ada beberapa file

In [34]:
from pkg import mod1

mod1.kitchen_sets

['fork', 'spoon', 'plate']

In [35]:
from pkg import mod1, mod2

print(mod1.kitchen_sets)
mod2.artist_name

['fork', 'spoon', 'plate']


'Queen'

In [36]:
from pkg import mod1 as m1

In [37]:
m1.kitchen_sets

['fork', 'spoon', 'plate']

In [ ]:
!pip install numpy

In [ ]:
!pip install pandas

## numpy

In [3]:
import numpy as np

In [85]:

a= np.array([1,2,4]) #harus dikurungin gini
a

array([1, 2, 4])

In [86]:
#tinggi= [1.7, 1.8, 2.0]
#berat =[60, 62, 65.4, 89]
# berat/tinggi  bakal error

tinggi= [1.7, 1.8, 2.0, 3.6]
berat =[60, 62, 65.4, 89]
np_tinggi=np.array(tinggi)
np_berat=np.array(berat)
np_berat/np_tinggi


array([35.29411765, 34.44444444, 32.7       , 24.72222222])

In [87]:
np.empty(4)

array([35.29411765, 34.44444444, 32.7       , 24.72222222])

In [2]:
print(np.arange(4,11,2))

[ 4  6  8 10]


In [ ]:
arr= np.array([1,2,3,4])
np.append(arr, [1,2,3])

array([1, 2, 3, 4, 1, 2, 3])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
np.delete(arr, 3)#based on index not number

array([1, 2, 3])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4])

In [4]:
#0-d/skalar

arr= np.array(4)
print(arr)

4


In [5]:
#1d vektor
arr= np.array ([4,2,3])
print(arr)

[4 2 3]


In [6]:
#2d matriks
arr = np.array ([[3,4,5],[5,7,6]])
print(arr)

[[3 4 5]
 [5 7 6]]


In [ ]:
arr.shape

In [7]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [11]:
#untuk cek dimensi, tulis variable terus .ndim
array_example.ndim

3

In [12]:
#istilah dn jumlah, angka sesuai shell dari luarnya. contoh yang dibawah
#itu 3 karena ada 3 baris kurus, 2 karena ada 2 baris di dalamnya, 4 karena ada 4 nomor 
array_example.shape

(3, 2, 4)

In [13]:
array_example.size


24

In [15]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [16]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [18]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [19]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [20]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [22]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [23]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [24]:
#soal slicing
arr = np.array([2,3,7,8,9])
print(arr[2:5])

[7 8 9]


In [26]:
print(arr[2:5:3])

[7]


In [30]:
print(arr[::2])

[2 7 9]


In [38]:
print(arr[:3:2]) #3 dikurang satu dulu

[2 7]


In [44]:
arr= np.array([[2,3,7,8,9],[1,3,6,8,7]])
print(arr[1, 1:4]) #sebelum , indezx pertama setelah , index di dalamnya

[3 6 8]


In [45]:
arr= np.array([[2,3,7,8,9],[1,3,6,8,7]])
print(arr[0, 1:4]) 

[3 7 8]


In [47]:
print(arr[2:4, 2])# 2:4 sama aja index 2 sampe 3

[]


In [48]:
print(arr[0:2, 2]) #0:2 sama aha 0-1 berarti index luar diambil semua

[7 6]


In [49]:
print(arr[1:4])

[[1 3 6 8 7]]


In [50]:
print(arr[1:4])
print(arr[1:3])

[[1 3 6 8 7]]
[[1 3 6 8 7]]


In [51]:
print(arr[1:4]) #diambil hanya dari row index 1
print(arr[0:3])#diambil dari row 0-2

[[1 3 6 8 7]]
[[2 3 7 8 9]
 [1 3 6 8 7]]


In [52]:
arr= np.array([[2,3,7,8,9],[1,3,6,8,7],[1,3,6,8,7]])
print(arr[1:2, 2:4])

[[6 8]]


In [54]:
arr= np.array([[2,3,7,8,9],[1,3,6,8,7],[1,3,6,8,7]])
print(arr[1:3, 2:4])

[[6 8]
 [6 8]]


In [55]:
a = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [56]:
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]])

In [57]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [58]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [59]:
data_1 = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])

In [60]:
#jadi 3 dimensi
new_arr= data_1.reshape(2,2,3)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [61]:
neww_arr= data_1.reshape(2,3,-1) #unknown division
print(neww_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [63]:
neww_arr.shape

(2, 3, 2)

In [73]:
def convert(fahr):
    cels = fahr * 1.8 + 32.0
    return cels
print(convert(32))


89.6


In [75]:
def convert(fahr,kelv):
    cels = fahr * 1.8 + 32.0
    cels2 = kelv -273.15
    return cels    
print(convert(32,20))


89.6


In [77]:
def convert(fahr,kelv):
    cels = fahr * 1.8 + 32.0
    cels2 = kelv -273.15
    return cels, cels2    
print(convert(32,20))

(89.6, -253.14999999999998)


In [89]:
def convert(fahr,kelv):
    cels = fahr * 1.8 + 32.0
    cels2 = kelv -273.15
    return cels, cels2    
print("Temperature in celcius ( C ) : ", convert(32,20))

Temperature in celcius ( C ) :  (89.6, -253.14999999999998)


In [80]:
def fahr_to_celsius(temp):
     return (temp - 32) * (5/9)
print(fahr_to_celsius(72))


22.22222222222222


In [90]:
def temp_converter(ftemp):
     ctemp = (ftemp - 32) * (5/9)
     ktemp = ctemp + 273.15
     return [ftemp, ktemp, ctemp]
print("Temperature in celcius ( C ) : ",temp_converter(72))


Temperature in celcius ( C ) :  [72, 295.3722222222222, 22.22222222222222]


In [82]:
def temp_converter(ftemp):
     ctemp = (ftemp - 32) * (5/9)
     ktemp = ctemp + 273.15
     return [ftemp, ktemp, ctemp]
print(temp_converter(72))


[72, 295.3722222222222, 22.22222222222222]


In [85]:
def inch_to_cent(inches):
    cent = inches * 2.54
    return cent
print(inch_to_cent(10))


25.4


In [84]:
def sum(numbers):
    total = 0
    for x in numbers:
        total += x
    return total
print(sum((8, 2, 3, 0, 7)))


20


In [88]:
def myfunc():
    st='jojon'
    y=35
    return st,y
a = myfunc()
print(a[0])

jojon
